### ISSUE TITLE
Default Dictionary.

### ISSUE THREAD

**Issue by VasilKotsov** [usemoslinux/aprelendo#195]
Can you make Glosbe to work as default dictionary?
It is a really helpful and accurate dictionary.
Thank you.

**Comment by usemoslinux** [comment]
I'll try doing that in the future. Right now, it seems the API is down due to a DDOS attack: https://glosbe.com/help/api

**Comment by usemoslinux** [comment]
Hi Vasil, just a quick note to let you know that I've changed entirely the way users interact with dictionaries in Aprelendo. Now, all dictionaries/translators are opened in a new tab instead of inside an iframe. Therefore, allowing you to use Aprelendo with virtually any online dictionary/translator, including Glosbe.
For added convenience, I have also included Glosbe in the "fast add" (or lightening) button in the "edit language" page.
Let me know if you find this new feature useful.
